theme: jekyll-theme-cayman
title: atlases of meaning
description: we are but protein-sheathed splashes of ocean raised from rock to breathe the sky, eaters of sun whose atoms were forged on an anvil of stars
